/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author farre
 */
public class DashboardContent extends javax.swing.JPanel {

    /**
     * Creates new form DashboardContent
     */
    public DashboardContent() {
        initComponents();
        
        // Set border agar ada jarak antar card
        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        // Pastikan panel mengisi penuh
        setPreferredSize(null);
        setLayout(new java.awt.GridLayout(2, 2, 20, 20));
        
        statDashboard5.setData("Total Barang", "1,284", " Unit", new java.awt.Color(220, 225, 255), "assets/barang-icon.png");
        statDashboard6.setData("Kategori", "24", " Grup", new java.awt.Color(200, 230, 200), "assets/kategori-icon.png");
        statDashboard7.setData("Stok Rendah", "18", " Item", new java.awt.Color(255, 200, 200), "assets/warning-icon.png");
        statDashboard8.setData("Aktivitas Hari Ini", "45", " Log", new java.awt.Color(255, 220, 180), "assets/activity-icon.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statDashboard5 = new Components.StatDashboard();
        statDashboard6 = new Components.StatDashboard();
        statDashboard7 = new Components.StatDashboard();
        statDashboard8 = new Components.StatDashboard();

        setLayout(new java.awt.GridLayout(2, 2));
        add(statDashboard5);
        add(statDashboard6);
        add(statDashboard7);
        add(statDashboard8);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.StatDashboard statDashboard5;
    private Components.StatDashboard statDashboard6;
    private Components.StatDashboard statDashboard7;
    private Components.StatDashboard statDashboard8;
    // End of variables declaration//GEN-END:variables
}
