/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author farre
 */
public class DashboardContent extends javax.swing.JPanel {

    /**
     * Creates new form DashboardContent
     */
    public DashboardContent() {
        initComponents();
        
        // Set border agar ada jarak antar card
        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        // Pastikan panel mengisi penuh
        setPreferredSize(null);
        setLayout(new java.awt.GridLayout(2, 2, 20, 20));
                
        refreshStatCard();        
    }
    
    private void refreshStatCard() {
        statDashboard1.setData("TOTAL KATEGORI", getTotalKategori()," Grup", new java.awt.Color(160, 250, 200), "assets/category-icon.png");
        statDashboard2.setData("BARANG TERDAFTAR", getTotalBarang()," Unit", new java.awt.Color(220, 225, 255), "assets/barang-icon.png");
        statDashboard3.setData("STOK RENDAH", getStokKritis(), " Unit", new java.awt.Color(255, 200, 200), "assets/danger-icon.png");
        statDashboard4.setData("AKTIVITAS HARI INI",getTotalLog() , " Log", new java.awt.Color(255, 220, 180), "assets/stats-up-icon.png");
    }

    private String getTotalKategori() {
        try {
            Connection conn = db.koneksi.getConnection();
            ResultSet rs = conn.createStatement().executeQuery("SELECT COUNT(*) FROM kategori");
            if (rs.next()) return String.valueOf(rs.getInt(1));
        } catch (Exception e) { e.printStackTrace(); }
        return "0";
    }

    private String getTotalBarang() {
        try {
            Connection conn = db.koneksi.getConnection();
            ResultSet rs = conn.createStatement().executeQuery("SELECT COUNT(*) FROM barang");
            if (rs.next()) return String.valueOf(rs.getInt(1));
        } catch (Exception e) { e.printStackTrace(); }
        return "0";
    }
    
    private String getStokKritis() {
        try {
            Connection conn = db.koneksi.getConnection();
            String sql = "SELECT COUNT(*) FROM barang WHERE stok <= stok_minimum";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return rs.getInt(1)+ "";
            System.out.println(rs.getInt(1));
        } catch (Exception e) { e.printStackTrace(); }
        return "0 Barang";
    }
    
    private String getTotalLog() {
        try {
            Connection conn = db.koneksi.getConnection();
            ResultSet rs = conn.createStatement().executeQuery(
                "SELECT (SELECT COUNT(*) FROM stok_masuk) + (SELECT COUNT(*) FROM stok_keluar) AS total"
            );
            if (rs.next()) return String.valueOf(rs.getInt("total"));
        } catch (Exception e) { e.printStackTrace(); }
        return "0";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statDashboard1 = new Components.StatDashboard();
        statDashboard2 = new Components.StatDashboard();
        statDashboard3 = new Components.StatDashboard();
        statDashboard4 = new Components.StatDashboard();

        setLayout(new java.awt.GridLayout(2, 2));
        add(statDashboard1);
        add(statDashboard2);
        add(statDashboard3);
        add(statDashboard4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.StatDashboard statDashboard1;
    private Components.StatDashboard statDashboard2;
    private Components.StatDashboard statDashboard3;
    private Components.StatDashboard statDashboard4;
    // End of variables declaration//GEN-END:variables
}
