/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Components.Sidebar;
import db.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author LENOVO
 */
public class MainFrame extends javax.swing.JFrame {
    
    private String role;
    private String nama;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    public MainFrame() {
        initComponents();
    }

    public MainFrame(String role, String nama) {

        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MainFrame.MAXIMIZED_BOTH);

        this.role = role;
        this.nama = nama;

        setupDashboard();
        
        sidebar1.setSidebarListener(new Sidebar.SidebarListener() {
        @Override
        public void onMenuClicked(String menuName) {
            if (menuName.equals("ManajemenBarang")) {
                
                View.ManajemenBarang halamanBarang = new View.ManajemenBarang();
                pnlMainContent.removeAll();
                pnlMainContent.setLayout(new java.awt.BorderLayout());
                pnlMainContent.add(halamanBarang, java.awt.BorderLayout.CENTER);
                halamanBarang.setSize(pnlMainContent.getSize());
                
                // Refresh UI
                pnlMainContent.revalidate();
                pnlMainContent.repaint();
                
            } else if (menuName.equals("ManajemenKategori")) {
            }
        }
    });
    }
    
    private void setupDashboard() {
        try {
            Connection conn = koneksi.getConnection();
            String sqlBarang = "SELECT COUNT(*) AS total FROM barang";
            PreparedStatement psBarang =
                    conn.prepareStatement(sqlBarang);
            ResultSet rsBarang =
                    psBarang.executeQuery();
            if (rsBarang.next()) {
                lblBarang.setText(
                        "Jumlah Barang : " + 
                        rsBarang.getString("total")
                );
            }
            String sqlKategori =
                    "SELECT COUNT(*) AS total FROM kategori";
            PreparedStatement psKategori =
                    conn.prepareStatement(sqlKategori);
            ResultSet rsKategori =
                    psKategori.executeQuery();
            if (rsKategori.next()) {
                lblKategori.setText(
                        "Jumlah Kategori : " +
                        rsKategori.getString("total")
                );
            }
        } catch (Exception e) {
            System.out.println(
                    "Error Dashboard: "
                    + e.getMessage()
            );
        }
        
        sidebar1.setUserInfo(nama, role);
        sidebar1.setMenuListener(e -> {
            String menu = ((javax.swing.JButton) e.getSource()).getText();
        });
        
        sidebar1.setOnLogout(e -> {
            dispose();
            new Login().setVisible(true);
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        sidebar1 = new Components.Sidebar();
        pnlMainContent = new javax.swing.JPanel();
        lblBarang = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBarang.setText("jLabel1");

        lblKategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKategori.setText("jLabel1");

        javax.swing.GroupLayout pnlMainContentLayout = new javax.swing.GroupLayout(pnlMainContent);
        pnlMainContent.setLayout(pnlMainContentLayout);
        pnlMainContentLayout.setHorizontalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        pnlMainContentLayout.setVerticalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    try {
        for (javax.swing.UIManager.LookAndFeelInfo info
                : javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(
                        info.getClassName()
                );
                break;
            }
        }

    } catch (ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex) {

        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() ->
        new MainFrame().setVisible(true)
    );
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JPanel pnlMainContent;
    private Components.Sidebar sidebar1;
    // End of variables declaration//GEN-END:variables
}
