/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author HP
 */
public class ManajemenBarang extends javax.swing.JPanel {

    /**
     * Creates new form ManajemenBarang
     */
    public ManajemenBarang() {
        initComponents();

        statCard1.setData("TOTAL BARANG", "1,284", new java.awt.Color(220, 225, 255), "C:\\Users\\HP\\Documents\\NetBeansProjects\\InventoriKu\\src\\main\\java\\assets\\barang-icon.png");
        statCard2.setData("KATEGORI", "12", new java.awt.Color(160, 250, 200), "C:\\Users\\HP\\Documents\\NetBeansProjects\\InventoriKu\\src\\main\\java\\assets\\category-icon.png");
        statCard3.setData("STOK KRITIS", "8 Barang", new java.awt.Color(255, 210, 210), "C:\\Users\\HP\\Documents\\NetBeansProjects\\InventoriKu\\src\\main\\java\\assets\\danger-icon.png");
        statCard4.setData("MUTASI HARI INI", "42 Items", new java.awt.Color(255, 220, 220), "C:\\Users\\HP\\Documents\\NetBeansProjects\\InventoriKu\\src\\main\\java\\assets\\stats-up-icon.png");
    
        setupTableBarang();
    }
    
    void setupTableBarang() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBarang.table.getModel();
        model.setRowCount(0); 
        
        String[] kolomBarang = {"Nama Barang", "Kategori", "Stok Saat Ini", "Satuan", "Aksi"};
    
        tblBarang.setupTable(kolomBarang);

        model.addRow(new Object[]{"Monitor Dell UltraSharp 27\"", "Elektronik", "3 - DI BAWAH THRESHOLD", "Unit", ""});
        model.addRow(new Object[]{"Keyboard Mekanik Keychron K2", "Elektronik", "24 - STOK AMAN", "Unit", ""});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        statCard1 = new Components.StatCard();
        statCard2 = new Components.StatCard();
        statCard3 = new Components.StatCard();
        statCard4 = new Components.StatCard();
        tblBarang = new Components.DataTable();

        setMaximumSize(new java.awt.Dimension(820, 2147483647));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 90));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 90));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 18));
        jPanel1.add(statCard1);
        jPanel1.add(statCard2);
        jPanel1.add(statCard3);
        jPanel1.add(statCard4);

        tblBarang.setEnabled(false);
        tblBarang.setPreferredSize(new java.awt.Dimension(820, 377));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                    .addComponent(tblBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private Components.StatCard statCard1;
    private Components.StatCard statCard2;
    private Components.StatCard statCard3;
    private Components.StatCard statCard4;
    private Components.DataTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
