/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Components.ToggleTransactionButton;
import java.awt.CardLayout;

/**
 *
 * @author farre
 */
public class ManageStockContent extends javax.swing.JPanel {

    /**
     * Creates new form ManageStockContent
     */
    private CardLayout cardLayout;
    private Components.InStockTransaction inStockPanel;
    private Components.OutStockTransaction outStockPanel;
    
    public ManageStockContent() {
        initComponents();      
        
        mainContent.setLayout(new CardLayout());
        cardLayout = (CardLayout) mainContent.getLayout();
                
        // Buat kedua panel SEKALI SAJA
        inStockPanel = new Components.InStockTransaction();
        outStockPanel = new Components.OutStockTransaction();                  
        
        // Tambahkan ke CardLayout dengan nama
        mainContent.add(inStockPanel, "in");
        mainContent.add(outStockPanel, "out");
        
        // Tampilkan default (Stok Masuk)
        cardLayout.show(mainContent, "in");
        
        // Setup listener untuk toggle button
        toggleTransactionButton2.setToggleTransactionButtonListener(new ToggleTransactionButton.ToggleTransactionButtonListener() {
            @Override
            public void toggleClicked(String mode) {                
                cardLayout.show(mainContent, mode);
            }
        });
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        toggleTransactionButton2 = new Components.ToggleTransactionButton();
        mainContent = new javax.swing.JPanel();

        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(30, 58, 138));
        label2.setText("Pengelolaan Stok");

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toggleTransactionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 407, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleTransactionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label2;
    private javax.swing.JPanel mainContent;
    private Components.ToggleTransactionButton toggleTransactionButton2;
    // End of variables declaration//GEN-END:variables
}
