/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Components.StockForm;
import db.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Utils.Session;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author farre
 */
public class InStockTransaction extends javax.swing.JPanel {

    /**
     * Creates new form TransactionContent
     */
    public InStockTransaction() {
        initComponents();
        
        stockForm2.setJudul("Stok Masuk");
        stockForm2.setLabelTarget("SUPPLIER");
        stockForm2.loadBarangData();
        stockForm2.loadSupplierData();

        // Setup tabel
        stockTable1.loadData();
        stockTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 40));

        // Listener tombol konfirmasi
        stockForm2.setConfirmation(e -> handleStockIn());
    }
    
    private void handleStockIn() {
        // Validasi
        String jumlahStr = stockForm2.getJumlah();
        if (jumlahStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int jumlah;
        try {
            jumlah = Integer.parseInt(jumlahStr);
            if (jumlah <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka positif!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idBarang = stockForm2.getIdBarang();
        if (idBarang == -1) {
            JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String supplier = stockForm2.getTarget();
        String catatan = stockForm2.getCatatan();
        java.util.Date tanggal = stockForm2.getTanggal();

        try {
            Connection conn = db.koneksi.getConnection();
            conn.setAutoCommit(false); // Mulai transaksi

            // 1. Insert ke stok_masuk
            String sqlInsert = "INSERT INTO stok_masuk (id_barang, id_user, jumlah, supplier, catatan, tanggal) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
            psInsert.setInt(1, idBarang);
            psInsert.setInt(2, Session.userId);
            psInsert.setInt(3, jumlah);
            psInsert.setString(4, supplier);
            psInsert.setString(5, catatan.isEmpty() ? null : catatan);
            if (tanggal != null) {
                psInsert.setDate(6, new java.sql.Date(tanggal.getTime()));
            } else {
                psInsert.setDate(6, new java.sql.Date(System.currentTimeMillis()));
            }
            psInsert.executeUpdate();

            // 2. Update stok barang (tambah)
            String sqlUpdate = "UPDATE barang SET stok = stok + ? WHERE id_barang = ?";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setInt(1, jumlah);
            psUpdate.setInt(2, idBarang);
            psUpdate.executeUpdate();

            conn.commit(); // Simpan perubahan
            conn.setAutoCommit(true);

            JOptionPane.showMessageDialog(this, "Stok masuk berhasil dicatat!");

            // Refresh tabel dan reset form
            stockTable1.loadData();
            stockForm2.resetForm();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mencatat stok masuk: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockForm2 = new Components.StockForm();
        stockTable1 = new Components.StockTable();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stockForm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stockTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockForm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(stockTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.StockForm stockForm2;
    private Components.StockTable stockTable1;
    // End of variables declaration//GEN-END:variables
}
