/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

/**
 *
 * @author HP
 */
public class Sidebar extends javax.swing.JPanel {
    
    public interface SidebarListener {
        void onMenuClicked(String menuName);
    }

    private SidebarListener listener;
    private java.awt.event.ActionListener menuListener;

    public Sidebar() {
        initComponents();
        
        btnKategori.addActionListener(e -> {
            if (listener != null) listener.onMenuClicked("ManajemenKategori");
        });
        
        btnStok.addActionListener(e -> {
            if (listener != null) listener.onMenuClicked("ManajemenStok");
        });
        
        btnLaporan.addActionListener(e -> {
            if (listener != null) listener.onMenuClicked("LaporanStok");
        });
        
        btnUser.addActionListener(e -> {
            if (listener != null) listener.onMenuClicked("ManajemenUser");
        });
    }
    
    public void setSidebarListener(SidebarListener listener) {
        this.listener = listener;
    }
    
    public void setUserInfo(String nama, String role) {
        lblNama.setText(nama);
        lblRole.setText(role);

        if (role != null && role.equalsIgnoreCase("STAFF")) {
            btnUser.setVisible(false);
        }
    }

    public void setMenuListener(java.awt.event.ActionListener listener) {
        this.menuListener = listener;
        btnBarang.addActionListener(listener);
        btnKategori.addActionListener(listener);
        btnStok.addActionListener(listener);
        btnLaporan.addActionListener(listener);
        btnUser.addActionListener(listener);
        btnDashboard.addActionListener(listener);
    }

    public void setOnLogout(java.awt.event.ActionListener listener) {
        btnLogout.addActionListener(listener);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNama = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnBarang = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNama.setText("jLabel1");

        lblRole.setText("jLabel1");

        btnBarang.setText("Manajemen Barang");
        btnBarang.addActionListener(this::btnBarangActionPerformed);

        btnKategori.setText("Manajemen Kategori");

        btnStok.setText("Stok Masuk/Keluar");
        btnStok.addActionListener(this::btnStokActionPerformed);

        btnLaporan.setText("Laporan Stok");

        btnUser.setText("Manajemen User");
        btnUser.addActionListener(this::btnUserActionPerformed);

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole)
                .addGap(17, 17, 17)
                .addComponent(btnDashboard)
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(btnBarang)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnKategori)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnStok)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLaporan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnUser)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout)
                    .addGap(8, 8, 8)))
        );

        lblNama.getAccessibleContext().setAccessibleName("lblNama");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.onMenuClicked("ManajemenBarang");
        }
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.onMenuClicked("ManajemenStok");
        }
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.onMenuClicked("Dashboard");
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.onMenuClicked("ManajemenUser");
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if (listener != null) {
            listener.onMenuClicked("LaporanStok");
        }
    }                                          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblRole;
    // End of variables declaration//GEN-END:variables
}
