/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class StatCard extends javax.swing.JPanel {

    /**
     * Creates new form StatCard
     */
    public StatCard() {
        initComponents();
    }
    
    public void setData(String title, String value, java.awt.Color color, String iconPath) {
        lblStatTitle.setText(title);
        lblStatValue.setText(value);
        pnlIcon.setBackground(color);                
        
        if (iconPath != null) {          
            java.net.URL imgUrl = getClass().getClassLoader().getResource(iconPath);            

            if (imgUrl != null) { 
                java.awt.Image img = new ImageIcon(imgUrl).getImage()
                .getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
                lblIcon.setIcon(new ImageIcon(img));
                lblIcon.setText("");
            } else {
                System.out.println("Gagal memuat icon: " + iconPath);                
            }
        }
    }

    public void setValue(String value) {
        lblStatValue.setText(value);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIcon = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblStatTitle = new javax.swing.JLabel();
        lblStatValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(230, 90));
        setPreferredSize(new java.awt.Dimension(230, 90));

        pnlIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setToolTipText("");
        lblIcon.setMaximumSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout pnlIconLayout = new javax.swing.GroupLayout(pnlIcon);
        pnlIcon.setLayout(pnlIconLayout);
        pnlIconLayout.setHorizontalGroup(
            pnlIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIconLayout.setVerticalGroup(
            pnlIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblStatTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatTitle.setForeground(new java.awt.Color(102, 102, 102));
        lblStatTitle.setText("test");

        lblStatValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatValue.setForeground(new java.awt.Color(25, 28, 30));
        lblStatValue.setText("test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatValue)
                    .addComponent(lblStatTitle))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatTitle)
                        .addGap(0, 0, 0)
                        .addComponent(lblStatValue))
                    .addComponent(pnlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblStatTitle;
    private javax.swing.JLabel lblStatValue;
    private javax.swing.JPanel pnlIcon;
    // End of variables declaration//GEN-END:variables
}
