/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

/**
 *
 * @author farre
 */
public class ToggleTransactionButton extends javax.swing.JPanel {

    private java.awt.event.ActionListener toggleListener;
    /**
     * Creates new form ToggleTransactionButton
     */
    public ToggleTransactionButton() {
        initComponents();
    }

    public interface ToggleTransactionButtonListener {
        void toggleClicked(String mode);
    }
    
    private ToggleTransactionButtonListener listener;

    public void setToggleTransactionButtonListener(ToggleTransactionButtonListener listener) {
        this.listener = listener;
    }
       
    public void setToggleListener(java.awt.event.ActionListener listener) {
        this.toggleListener = listener;

        inButton.addActionListener(listener);
        outButton.addActionListener(listener);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();

        inButton.setBackground(new java.awt.Color(30, 58, 138));
        inButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        inButton.setForeground(new java.awt.Color(255, 255, 255));
        inButton.setText("Stok Masuk");
        inButton.addActionListener(this::inButtonActionPerformed);

        outButton.setBackground(new java.awt.Color(30, 58, 138));
        outButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        outButton.setForeground(new java.awt.Color(255, 255, 255));
        outButton.setText("Stok Keluar");
        outButton.addActionListener(this::outButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(inButton)
                .addGap(18, 18, 18)
                .addComponent(outButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(inButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(outButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inButtonActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.toggleClicked("in");
        }
    }//GEN-LAST:event_inButtonActionPerformed

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.toggleClicked("out");
        }
    }//GEN-LAST:event_outButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inButton;
    private javax.swing.JButton outButton;
    // End of variables declaration//GEN-END:variables
}

